apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-delete-tasks-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-delete-tasks-api
  template:
    metadata:
      labels:
        app: todo-delete-tasks-api
    spec:
      containers:
      - name: todo-delete-tasks-api
        image: gssacr.azurecr.io/todo-delete-tasks-api:19
        ports:
        - containerPort: 8000
        env: 
        - name: CONNECTION_STRING
          value: "Driver={ODBC Driver 18 for SQL Server};Server=tcp:gssserver.database.windows.net,1433;Database=gssdb;Uid=CloudSAa341d8be;Pwd=trivvy2025@;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;"
