apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-get-task-api
  labels:
    app: todo-get-task-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-get-task-api
  template:
    metadata:
      labels:
        app: todo-get-task-api
    spec:
      containers:
      - name: todo-get-task-api
        image: gssacr.azurecr.io/gettaskstodomicroservice:19
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: CONNECTION_STRING
          value: "Driver={ODBC Driver 18 for SQL Server};Server=tcp:gssserver.database.windows.net,1433;Database=gssdb;Uid=CloudSAa341d8be;Pwd=trivvy2025@;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;"
